name: MWE

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Get LCov
        run: |
          wget https://github.com/linux-test-project/lcov/releases/download/v1.16/lcov-1.16.tar.gz
          tar -xzf lcov-1.16.tar.gz
          cd lcov-1.16
          sudo make install

      - name: Configure
        run: |
          cmake -S . -B build \
            -DCMAKE_CXX_STANDARD=14 \
            -DCMAKE_BUILD_TYPE=Coverage
      
      - name: Build
        run: cmake --build build -j4

      - name: Test
        run: |
          python -m pip install pytest
          pytest test_calc.py
          
      - name: Prepare coverage
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '*/tests/*' '*/examples/*' '/usr/*' --output-file coverage.info
          lcov --list coverage.info
        working-directory: build
